Tortoise: fix 'set heading' to normalize to [0,360) rangea
attention @frankduncan, this fixes that weird slightly-wrong-xcor
thing you found earlier today

to find this, it was key to change this:
  testCommand("repeat 10 [ go ]")
to:
  for (_ <- 1 to 10)
    testCommand("go")

before the change, the error said:
    java.lang.AssertionError: turtles.31.xcor
  Expected: -0.02335152929065968
       got: -0.023351529290659777
afterwards it said:
    java.lang.AssertionError: turtles.31.heading
  Expected: 183
       got: -177
   ; turtles.31.xcor
  Expected: 0.08533821164244618
       got: 0.08533821164244608
at which point the cause became easy to see.